# Generated by Django 2.0.9 on 2018-10-25 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(upload_to='photos')),
                ('weight', models.PositiveSmallIntegerField()),
                ('has_pet', models.BooleanField()),
                ('favorite_animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Animal')),
                ('hair_color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Color')),
            ],
        ),
    ]
