# Generated by Django 2.0.9 on 2018-10-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='profile_photo',
            field=models.ImageField(upload_to='app/photos'),
        ),
    ]
